### PR TITLE
Fix for downloaded chapters not saving scroll position.

### PR DESCRIPTION
**Pull request by DonielMoins**
Fixed by scrolling in offline reader.
Badly written but works sooo ;p

### CODE REVIEW

**Comment by DonielMoins** [comment]
Btw I'm still learning Git so pls give me tips. Thanks!

**Comment by gmathi** [comment]
That reset novel is interesting, promote that too? what do you think? @DonielMoins

**Comment by DonielMoins** [comment]
it's a work in progress, but I can't seem to figure it out. Need to look
more into the codebase and put it together properly.
I can delete the chapter but I can't add it back properly.
I could probably do this with the DB tables (I don't know how to write SQL
code yet) and then I'll syncNovels().

**Comment by DonielMoins** [comment]
Added it : )

**Comment by DonielMoins** [comment]
Sorry, ill figure out how to Pull properly

**Pull request closed without merging**
