### PR TITLE
#78 and #79

### PR DESCRIPTION
**Pull request by Guiorgy**
- #78 Disable swipe remove
- #79 Slightly increase the space for the timestamps:

Screenshot_20200113-185958_Novel Library
&nbsp;|
V
Screenshot_20200113-205630_Novel Library (devel)

- Fix a typo "_novels __with__ be moved to_" to "_novels __will__ be moved to_"
- Added a function _scrollToFirstUnread_ as an optional alternative for _scrollToBookmark_

### CODE REVIEW

**Comment by gmathi** [comment]
Did you do a local test on the changes that you have done?

**Comment by Guiorgy** [comment]
I renamed the app one a separate branch and built a debug apk and tested a little, by that I mean like 5 minutes test

**Comment by gmathi** [comment]
OK Looks good! Will include this as part of next release

**Comment by gmathi** [comment]
> I renamed the app one a separate branch and built a debug apk and tested a little, by that I mean like 5 minutes test. I still have it on my phone, could use it for a while to see, if you want?
> 
> PS. I didn't entirely remove the swipe and left it for 'Novel Section' as, at least for now, it is a one screen activity, so there's no conflict for the swipe
> 
> Edit: there's also this **listitem_library_new.xml** listitem, but as far as I can tell there's no reference to it anywhere, so I left that untouched. What do you think?

That was supposed to be a new design, but I didn't get chance to develop it...

**Comment by Guiorgy** [comment]
Then I'll be closing the 2 issues I opened, ok?

**Comment by gmathi** [comment]
Sure

**Pull request merged**
